// <auto-generated />
using System;
using Antigravity.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Antigravity.Api.Migrations.PostgreSql
{
    [DbContext(typeof(FontaneriaContext))]
    [Migration("20260119224117_SyncDateTimeOffset")]
    partial class SyncDateTimeOffset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Antigravity.Api.Models.Aviso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("codcli");

                    b.Property<DateTimeOffset?>("CommitmentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("commitment_time");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_hours");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Avisos", (string)null);
                });

            modelBuilder.Entity("Antigravity.Api.Models.Break", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("EndLat")
                        .HasColumnType("numeric")
                        .HasColumnName("end_lat");

                    b.Property<decimal?>("EndLng")
                        .HasColumnType("numeric")
                        .HasColumnName("end_lng");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal?>("StartLat")
                        .HasColumnType("numeric")
                        .HasColumnName("start_lat");

                    b.Property<decimal?>("StartLng")
                        .HasColumnType("numeric")
                        .HasColumnName("start_lng");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkDayId")
                        .HasColumnType("integer")
                        .HasColumnName("work_day_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkDayId");

                    b.ToTable("Breaks", (string)null);
                });

            modelBuilder.Entity("Antigravity.Api.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Antigravity.Api.Models.SiteVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attachment_path");

                    b.Property<int?>("AvisoId")
                        .HasColumnType("integer")
                        .HasColumnName("aviso_id");

                    b.Property<decimal?>("CheckInLat")
                        .HasColumnType("numeric")
                        .HasColumnName("check_in_lat");

                    b.Property<decimal?>("CheckInLng")
                        .HasColumnType("numeric")
                        .HasColumnName("check_in_lng");

                    b.Property<DateTimeOffset>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<decimal?>("CheckOutLat")
                        .HasColumnType("numeric")
                        .HasColumnName("check_out_lat");

                    b.Property<decimal?>("CheckOutLng")
                        .HasColumnType("numeric")
                        .HasColumnName("check_out_lng");

                    b.Property<DateTimeOffset?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteName")
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkDayId")
                        .HasColumnType("integer")
                        .HasColumnName("work_day_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkDayId");

                    b.ToTable("SiteVisits", (string)null);
                });

            modelBuilder.Entity("Antigravity.Api.Models.WorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("EndLat")
                        .HasColumnType("numeric")
                        .HasColumnName("end_lat");

                    b.Property<decimal?>("EndLng")
                        .HasColumnType("numeric")
                        .HasColumnName("end_lng");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal?>("StartLat")
                        .HasColumnType("numeric")
                        .HasColumnName("start_lat");

                    b.Property<decimal?>("StartLng")
                        .HasColumnType("numeric")
                        .HasColumnName("start_lng");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.HasKey("Id");

                    b.ToTable("WorkDays", (string)null);
                });

            modelBuilder.Entity("Antigravity.Api.Models.Aviso", b =>
                {
                    b.HasOne("Antigravity.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Antigravity.Api.Models.Break", b =>
                {
                    b.HasOne("Antigravity.Api.Models.WorkDay", "WorkDay")
                        .WithMany("Breaks")
                        .HasForeignKey("WorkDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("Antigravity.Api.Models.SiteVisit", b =>
                {
                    b.HasOne("Antigravity.Api.Models.WorkDay", "WorkDay")
                        .WithMany("SiteVisits")
                        .HasForeignKey("WorkDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("Antigravity.Api.Models.WorkDay", b =>
                {
                    b.Navigation("Breaks");

                    b.Navigation("SiteVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
